vsphere_server     = "10.76.221.238"
vsphere_user       = "root"
vsphere_password   = "Test1234!"
vsphere_dc         = "PacketDatacenter"
datacenter         = "pool0"
cluster            = ""
network_name       = "VM Network"
ubuntu_name        = "tf-edu-ubuntu"
